[mcp_servers.godot]
command = "npx"
args = ["@coding-solo/godot-mcp"]

[mcp_servers.godot.env]
GODOT_PATH = "F:/文件下载/编程工具/Godot_v4.6.2-stable_win64.exe"

[mcp_servers.toutiao]
command = "python"
args = [
    'F:\toutiao_mcp_server\start_server.py',
    "--transport",
    "stdio",
]
